### ISSUE TITLE
[dev.icinga.com #8864] update lwrp examples

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#100]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8864

**Created by vkhatri on 2015-03-25 18:33:17 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2015-03-25 18:33:17 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Closing, too old to capture the requirement.
