### ISSUE TITLE
[dev.icinga.com #9216] add icingaweb2 install via package

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#120]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9216

**Created by vkhatri on 2015-05-02 17:58:10 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2015-05-02 17:58:10 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Change committed, closing.
