### ISSUE TITLE
[dev.icinga.com #10572] Allow use of packages instead of pulling directly from Git

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#180]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10572

**Created by jorhett on 2015-11-08 18:36:37 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2015-11-15 19:17:33 +00:00 (in Redmine)_

---

This patch adds the ability to install from packages, while also retaining the ability to pull from Git. It also adds the ability to checkout instead of sync, such as when someone has a local patch they've submitted in a PR which shouldn't be overwritten every time Chef runs ;-)

https://github.com/Icinga/chef-icinga2/pull/41

**Comment by vkhatri** [comment]
Changes committed to recipe server_web2. Closing.
