### ISSUE TITLE
[dev.icinga.com #10582] icinga2::server installment on Ubuntu Trusty won't run due to automatically enabled Apache php5 module 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#182]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10582

**Created by trish on 2015-11-09 14:24:01 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-05-11 14:35:45 +00:00 (in Redmine)_

---

When libapache2-mod-php5 is installed by icinga2::server\_os\_packages the mod-php5 module is being enabled automatically, and leads to the following error on Ubuntu Trusty:

'Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe. You need to recompile PHP.'

Exclusion of mod-php5 from \['icinga2'\]\['apache\_modules'\] and \['rrdtool'\]\['packages'\] does not help since icinga2::server\_os\_packages does not honour these settings.

Workaround:

apache\_module 'php5' do
enable false
end

**Comment by vkhatri** [comment]
Done.
