### ISSUE TITLE
[dev.icinga.com #10587] setup both release and snapshot repositories by default

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#184]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10587

**Created by vkhatri on 2015-11-10 06:22:57 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2015-11-10 06:22:57 +00:00 (in Redmine)_

---

I am yet to start working on it, but i think it will be quite useful.

\`release\` repo will be enabled and \`snapshot\` repo will be disabled by default.

Each package (icinga2, classic ui, web2 ..) can have an attribute to use \`release\` or \`snapshot\` repo which will control --enablerepo & --disablerepo for \`package\` resource as an override to \`node\['icinga2'\]\['build\_type'\]\`.

I am not entirely sure how it will be played out for \`apt\`, i am going to give it a day or two before releasing \`v2.7.0\`.

**Comment by vkhatri** [comment]
Not a requirement, leaving it for later.
