### ISSUE TITLE
[dev.icinga.com #10798] env_filter_node_vars resource example

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#191]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10798

**Created by rnekkanti on 2015-12-09 00:37:59 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-01-10 14:20:19 +00:00 (in Redmine)_

---

Hello,

Could you please let me know what hash key-value pair to use to filter nodes based on a specific domain. For example, to add all nodes in a chef environment with attribute node\['domain'\] = abc.com. I have tried multiple possibilities but with no luck.

env\_filter\_node\_vars = {'domain' =&gt; 'abc.com'}
env\_filter\_node\_vars {'domain' 'abc.com'}
env\_filter\_node\_vars {:domain, 'abc.com'}

None off the above seem to work.

Thanks,
Rajiv.

**Comment by vkhatri** [comment]
Please open new issue if suggested solution did not work.
