### ISSUE TITLE
[dev.icinga.com #11834] Add lwrp envendpoint / envzone lwrp for environment resource

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#202]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11834

**Created by tsupertramp on 2016-05-24 15:21:24 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-07-21 15:10:09 +00:00 (in Redmine)_

---

Hey Ho,

first of all. Thanks for awesome environment provider which allowed me
to remove our custom templates for icinga(1).

At the moment i want to add icinga2 client on all nodes and i work on a deployable client recipe.
I realized that this is not enough as the environment provider does not create
zone/endpoints for all clients.

In a first draft i would add a custom var to every host (remote\_client) containing the endpoint.
Add the Endpoint (named equal as the environment + node\_name).
And add a zone containing the endpoint + master.
"As a matter of trust the client Endpoint is a member of its own Zone object which gets the master zone configured as parent.
That way the master knows how to connect to the client and where to execute the check commands."

I looked through the resources and already started my work today. Anything I should care about? :)
Will continue my work tomorrow.

Greetings, Thomas

**Comment by tsupertramp** [comment]
Pull Request was merged - Please close

**Comment by lazyfrosch** [comment]
@tsupertramp thanks for pointing that out
