### ISSUE TITLE
[dev.icinga.com #11836] PerfdataWriter library nil bug

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#203]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11836

**Created by spkane on 2016-05-24 22:28:27 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-07-21 15:21:29 +00:00 (in Redmine)_

---

The following recipe, with or without the library line, is creating an invalid object config, with library set to nil.

    icinga2_feature 'perfdata'

    icinga2_perfdatawriter 'pnp' do
      library 'perfdata'
      host_perfdata_path '/var/spool/icinga2/perfdata/host-perfdata'
      service_perfdata_path '/var/spool/icinga2/perfdata/service-perfdata'
      host_format_template 'DATATYPE::HOSTPERFDATA\tTIMET::$icinga.timet$\tHOSTNAME::$host.name$\tHOSTPERFDATA::$host.perfdata$\tHOSTCHECKCOMMAND::$host.check_command$\tHOSTSTATE::$host.state$\tHOSTSTATETYPE::$host.state_type$'
      service_format_template 'DATATYPE::SERVICEPERFDATA\tTIMET::$icinga.timet$\tHOSTNAME::$host.name$\tSERVICEDESC::$service.name$\tSERVICEPERFDATA::$service.perfdata$\tSERVICECHECKCOMMAND::$service.check_command$\tHOSTSTATE::$host.state$\tHOSTSTATETYPE::$host.state_type$\tSERVICESTATE::$service.state$\tSERVICESTATETYPE::$service.state_type$'
      rotation_interval '1d'
    end

The resulting object file looks like this:

    /**
     * This file is managed by Chef.
     * Do NOT modify this file directly.
    */

    /**
     * PerfdataWriter Object.
    */

    library nil

    object PerfdataWriter "pnp" {
      host_perfdata_path = "/var/spool/icinga2/perfdata/host-perfdata"
      service_perfdata_path = "/var/spool/icinga2/perfdata/service-perfdata"
      host_format_template = "DATATYPE::HOSTPERFDATA\\tTIMET::$icinga.timet$\\tHOSTNAME::$host.name$\\tHOSTPERFDATA::$host.perfdata$\\tHOSTCHECKCOMMAND::$host.check_command$\\tHOSTSTATE::$host.state$\\tHOSTSTATETYPE::$host.state_type$"
      service_format_template = "DATATYPE::SERVICEPERFDATA\\tTIMET::$icinga.timet$\\tHOSTNAME::$host.name$\\tSERVICEDESC::$service.name$\\tSERVICEPERFDATA::$service.perfdata$\\tSERVICECHECKCOMMAND::$service.check_command$\\tHOSTSTATE::$host.state$\\tHOSTSTATETYPE::$host.state_type$\\tSERVICESTATE::$service.state$\\tSERVICESTATETYPE::$service.state_type$"
      rotation_interval = 1d
    }

The fix is to change the library line to look like this:

    library "perfdata"

For the moment the work around it to drop this in as a template or cookbook\_file.

**Comment by vkhatri** [comment]
Done.
