### ISSUE TITLE
[dev.icinga.com #11961] Add missing chefspec resources

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#208]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11961

**Created by tsupertramp on 2016-06-16 12:58:03 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-16 12:58:03 +00:00 (in Redmine)_

---

Working on it..

**Comment by vkhatri** [comment]
Please create a new one if required.
