### ISSUE TITLE
[dev.icinga.com #12609] Cannot do core_install on Ubuntu 14 LTS

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#212]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12609

**Created by joekmiller on 2016-08-31 21:22:33 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 11:07:30 +00:00 (in Redmine)_

---

"server" recipe fails on Ubuntu 14 LTS. I've tried various versions and even adding the icinga to sources list and it still fails.

    * apt_package[icinga2] action install

     ================================================================================

     Error executing action `install` on resource 'apt_package[icinga2]'

     ================================================================================

     Mixlib::ShellOut::ShellCommandFailed

     ------------------------------------

     Expected process to exit with [0], but received '100'

     ---- Begin output of apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 ----

     STDOUT: Reading package lists...

     Building dependency tree...

     Reading state information...

     STDERR: E: Version '2.4.1-1~ppa1~trusty1' for 'icinga2' was not found

     ---- End output of apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 ----

     Ran apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 returned 100

     Cookbook Trace:

     ---------------

     /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'

     /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'

     /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'

     /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'

     /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'    

    Resource Declaration:

    ---------------------    
    # In /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/icinga2/recipes/core_install.rb

      46: package 'icinga2' do

      47:   version node['icinga2']['version'] + node['icinga2']['icinga2_version_suffix'] unless node['icinga2']['ignore_version']

      48:   notifies :restart, 'service[icinga2]', :delayed

      49: end

     Compiled Resource:

     ------------------

     # Declared in /tmp/vagrant-chef/551d73b9e4affd814c9384b322d68e5a/cookbooks/icinga2/recipes/core_install.rb:46:in `from_file'

     apt_package("icinga2") do

       package_name "icinga2"

       action [:install]

       retries 0

       retry_delay 2

       default_guard_interpreter :default

       declared_type :package

       cookbook_name :icinga2

       recipe_name "core_install"

       version "2.4.1-1~ppa1~trusty1"

     end

     Platform:

     ---------

     x86_64-linux

     [2016-08-31T21:11:00+00:00] INFO: Running queued delayed notifications before re-raising exception

     Running handlers:
     [2016-08-31T21:11:00+00:00] ERROR: Running exception handlers
     Running handlers complete

     [2016-08-31T21:11:00+00:00] ERROR: Exception handlers complete
     Chef Client failed. 0 resources updated in 04 seconds
     [2016-08-31T21:11:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    ==> monitoring: [2016-08-31T21:11:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    ==> monitoring: [2016-08-31T21:11:00+00:00] ERROR: apt_package[icinga2] (icinga2::core_install line 46) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
     ---- Begin output of apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 ----
     STDOUT: Reading package lists...
     Building dependency tree...
     Reading state information...
     STDERR: E: Version '2.4.1-1~ppa1~trusty1' for 'icinga2' was not found
     ---- End output of apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 ----
     Ran apt-get -q -y install icinga2=2.4.1-1~ppa1~trusty1 returned 100
     [2016-08-31T21:11:01+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by vkhatri** [comment]
Closing. N/A.
