### ISSUE TITLE
[dev.icinga.com #12689] issue tracker for PR #58

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#213]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12689

**Created by vkhatri on 2016-09-10 11:27:56 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-13 13:09:23 +00:00 (in Redmine)_

---

@bsheqa This would not work with the current resource notifications (e.g. service). Last time i checked it also caused issues when multiple resources try to update a common file, for which the only other solution is to create a separate config file per resource definition (which will result in 100s of files).

I will give it another try and see if there is any recommended way.

But, this PR will break the cookbook.

**Comment by vkhatri** [comment]
PR Closed.
