### ISSUE TITLE
[dev.icinga.com #12691] enable travis build

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#214]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12691

**Created by vkhatri on 2016-09-10 15:12:13 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-18 14:23:26 +00:00 (in Redmine)_

---

Hello Michael!

Could you please help enabling Travis build for chef-icinga2?

https://travis-ci.org/Icinga/chef-icinga2

Thanks in advance.

**Comment by vkhatri** [comment]
Thank you for enabling Travis CI. Closing.
