### ISSUE TITLE
[dev.icinga.com #12779] mysql package is required for server_ido recipe

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#215]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12779

**Created by vkhatri on 2016-09-24 12:21:09 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-24 12:21:09 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Done.
