### ISSUE TITLE
[dev.icinga.com #12780] install icingaweb2 icingacli packages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#216]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12780

**Created by vkhatri on 2016-09-24 12:22:24 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-24 12:22:24 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Completed.
