### ISSUE TITLE
[dev.icinga.com #12781] determine icingaweb2 ubuntu version

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#217]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12781

**Created by vkhatri on 2016-09-25 01:15:10 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 01:15:10 +00:00 (in Redmine)_

---

Current Ubuntu icingaweb2 version \`2.3.4+fix-1~ppa1404+1\` does not match with rhel platforms.

**Comment by vkhatri** [comment]
Completed.
