### ISSUE TITLE
[dev.icinga.com #12782] always remove default enabled feature ido-DB

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#218]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12782

**Created by vkhatri on 2016-09-25 01:16:31 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 01:16:31 +00:00 (in Redmine)_

---

default ido feature needs to be disabled in favor of custom ido mysql connection, which allows to define db parameters

**Comment by vkhatri** [comment]
Completed.
