### ISSUE TITLE
[dev.icinga.com #12784] enable feature command

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#220]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12784

**Created by vkhatri on 2016-09-25 01:19:04 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 01:19:04 +00:00 (in Redmine)_

---

requirement for icingaweb2

**Comment by vkhatri** [comment]
Done.
