### ISSUE TITLE
[dev.icinga.com #12785] update to latest release

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#221]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12785

**Created by vkhatri on 2016-09-25 04:19:02 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 04:19:15 +00:00 (in Redmine)_

---

2.5.4-1
2.3.4-1

**Comment by vkhatri** [comment]
No action required.
