### ISSUE TITLE
[dev.icinga.com #12788] do not include recipe server_pnp unless classis_ui and pnp

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#223]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12788

**Created by vkhatri on 2016-09-25 11:11:45 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 11:11:45 +00:00 (in Redmine)_

---

include recipe server\_pnp only if node\['icinga2'\]\['pnp'\] && if node\['icinga2'\]\['classic\_ui'\]\['enable'\]

**Comment by vkhatri** [comment]
Change committed, closing.
