### ISSUE TITLE
[dev.icinga.com #12790] install_mysql_client and load_schema  should be true for kitchen web2 suites

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#225]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12790

**Created by vkhatri on 2016-09-25 13:11:26 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 13:11:26 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Released. Closing.
