### ISSUE TITLE
[dev.icinga.com #12791] add kitchen suite for web2 source / package install methods

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#226]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12791

**Created by vkhatri on 2016-09-25 13:18:34 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 13:18:34 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Change committed. Closing.
