### ISSUE TITLE
[dev.icinga.com #12792] write specs for ido and web2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#227]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12792

**Created by vkhatri on 2016-09-25 14:17:04 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 14:17:04 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Closing for now, will create a new one.
