### ISSUE TITLE
[dev.icinga.com #12794] add db port to ido schema load

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#228]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12794

**Created by vkhatri on 2016-09-25 23:34:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-25 23:34:36 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Change applied, closing.
