### ISSUE TITLE
[dev.icinga.com #12795] deprecate node.set

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#229]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12795

**Created by vkhatri on 2016-09-25 23:36:40 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-25 23:36:40 +00:00 (in Redmine)_

---

**Comment by vkhatri** [comment]
Released. Closing.
