### ISSUE TITLE
[dev.icinga.com #12796] disable classic_ui by default

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#230]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12796

**Created by vkhatri on 2016-09-25 23:42:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-25 23:42:13 +00:00 (in Redmine)_

---

disabling and documenting

**Comment by vkhatri** [comment]
Released in v2.9.1
