### ISSUE TITLE
[dev.icinga.com #12812] update .kitchen.yml file for recent changes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#231]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12812

**Created by vkhatri on 2016-09-27 18:02:12 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-27 18:02:12 +00:00 (in Redmine)_

---

Add different suited for
- server
- client
- classicui
- web2-package
- web2-source

**Comment by vkhatri** [comment]
Closing for now, will be part of kitchen rework in favor of chefdk and dokken.
