### ISSUE TITLE
[dev.icinga.com #12813] publish new cookbook version v2.9.1

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#232]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12813

**Created by vkhatri on 2016-09-27 18:04:34 +00:00**

Assignee: _vkhatri_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-27 18:04:34 +00:00 (in Redmine)_

---

Update README for v2.9.1 changes.

**Comment by vkhatri** [comment]
Closing, cookbook uploaded to supermarket.
