### ISSUE TITLE
[dev.icinga.com #12949] contents of templates.conf not managed, leading to re-defined objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#236]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12949

**Created by pavo on 2016-10-20 15:59:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-21 16:03:35 +00:00 (in Redmine)_

---

Hi,

I'm pretty new to Icinga2 and the cookbook, so I might be missing something.

The issue I'm observing is that when using included server recipe example, duplicate definition is created causing icinga2 to fail to start. The error I'm getting is
critical/config: Error: Object 'mail-host-notification' of type 'Notification' re-defined: in /etc/icinga2/objects.d/notification\_template.conf: 10:1-10:46; previous definition: in /etc/icinga2/conf.d/templates.conf: 46:1-46:46

While /etc/icinga2/objects.d/notification\_template.conf is managed by chef, contents of /etc/icinga2/conf.d/templates.conf are left as is, as provided by the package during installation.

Steps to reproduce:

-   have a clean Ubuntu box
-   put these 2 recipes in the node's run\_list: recipe\[icinga2::server\], recipe\[icinga2\_server\] (the latter is taken from the included example)
-   run chef-client

Thanks

**Comment by vkhatri** [comment]
Will update the documentation.

**Comment by vkhatri** [comment]
I think you meant to say setting ` node['icinga2']['disable_conf_d']` to true.
It is fair to set it `true` as default resources are also created by cookbook.

Please feel free to submit a PR.

**Comment by vkhatri** [comment]
Cookbook updated.
