### ISSUE TITLE
[dev.icinga.com #12983] After use server_ido_schema recipe `icinga2 feature list` show wrong listing

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#237]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12983

**Created by Cyberflow on 2016-10-25 14:35:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-25 14:35:43 +00:00 (in Redmine)_

---

recipe server\_do\_schema put idoMysqlConnection object to /etc/icinga2/object.d directory. this leads to wrong listing icinga2 command from shell.
Test on Ubuntu 14.04. Cookbook release version from supermarket.chef.io

**Comment by vkhatri** [comment]
Please provide more info. What do you mean by `wrong listing icinga2 command from shell`?

**Comment by vkhatri** [comment]
Please reopen if required.
