### ISSUE TITLE
[dev.icinga.com #13679] Allow wrapping of the template of Icinga2Instance resources.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#239]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13679

**Created by fretb on 2016-12-19 14:37:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-19 14:39:21 +00:00 (in Redmine)_

---

I found there was no way to specify the cookbook to use for an Icinga2Instance resource template, as exists for the Icinga2Environment. (https://github.com/Icinga/chef-icinga2/blob/master/libraries/provider\_environment.rb#L89)

I've made a pull request at https://github.com/Icinga/chef-icinga2/pull/66.

**Comment by vkhatri** [comment]
PR Merged.
