### ISSUE TITLE
[dev.icinga.com #13865] PHP 5.5 dependency issues on Ubuntu 16.04, we should use 5.6.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/chef-icinga2#240]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13865

**Created by fretb on 2017-01-03 22:31:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-03 22:31:59 +00:00 (in Redmine)_

---

Php 5.5 has dependency issues on Ubuntu 16.04 in combination with the ondrej ppa. The dependency issues are concerning php-apcu and php-yac. As icingaweb2 is php 5.6 compatible, and 5.6 is present in the ondrej ppa, I've made a PR.

https://github.com/Icinga/chef-icinga2/pull/69

**Comment by cyberflow** [comment]
Hello,
I tried to find php5.X in xenial, but can't. Do you sure that it's right version? I can find only php7 in xenial.

http://packages.ubuntu.com/search?suite=xenial&arch=any&searchon=names&keywords=php5

**Comment by Datamancer1110** [comment]
My pull request (https://github.com/Icinga/chef-icinga2/pull/246) should resolve this ticket

**Comment by vkhatri** [comment]
@cyberflow Closing in favor of PR #246 

👍 

Will publish a new cookbook version soon.
