### ISSUE TITLE
Error executing action `run` on resource 'ruby_block[set php timezone]'

### ISSUE THREAD

**Issue by luijar** [Icinga/chef-icinga2#244]
Recipe: **icinga2::server_web2**
  directory[/etc/icingaweb2] action create (up to date)
  directory[/var/log/icingaweb2] action create (up to date)
  file[/etc/icingaweb2/setup.token] action create (up to date)  
  ruby_block[set php timezone] action run
    
    Error executing action `run` on resource 'ruby_block[set php timezone]'
        
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

[2017-01-18T12:31:13+00:00] ERROR: ruby_block[set php timezone] (icinga2::server_web2 line 53) had an error: NoMethodError: undefined method `[]' for nil:NilClass

This machine is using Ruby: 2.2.3. Could this be the problem?

**Comment by luijar** [comment]
Tried with latest ruby, the same issue happens when running chef-client

**Comment by vkhatri** [comment]
@luijar could you please share the os details?

**Comment by luijar** [comment]
There's a null guard check that you guys need to add I think. I was able to get passed this problem my explicitly setting the: 

node['time']['timezone'] = 'UTC'

You guys I guess assumed that users had node['time'] defined. I got passed this already but perhaps you need to implement a simple check in case node['time'] is not defined. 

Thanks!

**Comment by vkhatri** [comment]
it would still help to know which OS version you are running, but a guard is indeed required.

**Comment by vkhatri** [comment]
Fix applied.
