### ISSUE TITLE
Error on `install` resource 'yum_package[icingacli] -> 'Version v2.3.4-1.el6 of icingacli not found

### ISSUE THREAD

**Issue by luijar** [Icinga/chef-icinga2#245]
Trying to use 2.9.1. Here's the error from chef-client:

    **Version v2.3.4-1.el6 of icingacli not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)**

Trace:
yum_package[icingacli] action install
    
   
    Error executing action `install` on resource 'yum_package[icingacli]'
   
    
    Chef::Exceptions::Package
    -------------------------
    Version v2.3.4-1.el6 of icingacli not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb
    
     88:   package 'icingacli' do
     89:     version cli_version
     90:     notifies :restart, 'service[icinga2]', :delayed
     91:     only_if { node['platform_family'] == 'rhel' }
     92:   end
     93: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb:88:in `from_file'
    
    yum_package("icingacli") do
      package_name "icingacli"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "icinga2"
      recipe_name "server_web2"
      version "v2.3.4-1.el6"
      flush_cache {:before=>false, :after=>false}
      only_if { #code block }
    end
    
    Platform:
    ---------
    x86_64-linux
    
Recipe: icinga2::service
  * service[icinga2] action restart
    
    
    Error executing action `restart` on resource 'service[icinga2]'
    
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service icinga2 restart ----
    STDOUT: Checking configuration: Not restarting Icinga 2 due to configuration errors. Check '/var/log/icinga2/startup.log' for details.
    STDERR: 
    ---- End output of /sbin/service icinga2 restart ----
    Ran /sbin/service icinga2 restart returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2/recipes/service.rb
    
     21: service 'icinga2' do
     22:   service_name node['icinga2']['service_name']
     23:   supports :status => true, :reload => true, :restart => true
     24:   action [:enable]
     25: end
     26: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2/recipes/service.rb:21:in `from_file'
    
    service("icinga2") do
      action [:enable]
      supports {:status=>true, :reload=>true, :restart=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "icinga2"
      pattern "icinga2"
      declared_type :service
      cookbook_name "icinga2"
      recipe_name "service"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2017-01-17T20:05:42+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-01-17T20:05:42+00:00] ERROR: Exception handlers complete
Chef Client failed. 14 resources updated in 48 seconds
[2017-01-17T20:05:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-01-17T20:05:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-01-17T20:05:42+00:00] ERROR: Chef::Exceptions::MultipleFailures
[2017-01-17T20:05:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by luijar** [comment]
Hey @dnsmichi I bumped up to 2.4.0, but I can't get to that error because I see this error with chef-icinga2 2.9.1 #244 If I get past that, then maybe I could verify this works. Any idea when someone can look into that issue. All we're doing is adding our dependency to 2.9.1

**Comment by dnsmichi** [comment]
I'm more of a user here with little Chef knowledge. Hopefully @vkhatri or @bobapple can help you more with that. (I would've taken the chance to test it for the first time ;))

**Comment by vkhatri** [comment]
@luijar  @dnsmichi  issue seems to be with the package version.

```shell
# yum search icingacli --showduplicates
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.dhakacom.com
 * extras: mirror.dhakacom.com
 * updates: mirror.dhakacom.com
=========================================================================================================== N/S Matched: icingacli ===========================================================================================================
icingacli-2.3.4-1.el6.noarch : Icinga CLI
icingacli-2.4.0-2.el6.noarch : Icinga CLI

  Name and summary matches only, use "search all" for everything.
```

cookbook is trying to install `2.3.4-1`, but available package version is `2.4.0-2`.

I also noticed that recipe `server_web2` do not have `node['icinga2']['ignore_version']` for `icingaweb2` and `icingacli` packages.

will have a fix for it shortly.

**Comment by luijar** [comment]
Thanks @vkhatri I was able to kind of get passed this issue by looking up the yum packages and setting the versions accordingly. Don't know why the previous releases were removed. After getting all versions correct, now I'm getting stuck with #248 

Thank you!

**Comment by dnsmichi** [comment]
@vkhatri in terms of versions, @lippserd is preparing 2.4.1 which fixes a couple of bugs introduced with 2.4.0 - if you can wait for that release until updating the Chef cookbook :)

**Comment by lippserd** [comment]
I'll tag the new version today.

**Comment by vkhatri** [comment]
it tends to reoccur in the future. e.g. current icinga2 version for rhel os family is `2.6.0-1` where for debian os family it is `2.6.0-2`. similarly, icingweb2 is not the same for debian and ubuntu.

attributes `default['icinga2']['web2']['version']` and `default['icinga2']['web2']['release']` further needs to be classified for `icingaweb2` and `icingacli` for a better version control.

```ruby
default['icinga2']['web2']['icingaweb2']['version']
default['icinga2']['web2']['icingaweb2']['release']

default['icinga2']['web2']['icingacli']['version']
default['icinga2']['web2']['icingacli']['release']
```

**Comment by vkhatri** [comment]
updated attributes:

```ruby
default['icinga2']['web2']['version']['icingaweb2'] = '2.4.1-1'
default['icinga2']['web2']['version']['icingacli'] = '2.4.1-1'
```

**Comment by vkhatri** [comment]
fix applied to upstream
