### ISSUE TITLE
Error executing action `enable` on resource 'icinga2_feature[command]'

### ISSUE THREAD

**Issue by luijar** [Icinga/chef-icinga2#248]
Getting this error running chef-client. My setup includes: 

chef-icinga2 = 2.9.1
ruby = 2.4.0
yum[icinga2] =   2.6.0-1.el6     
yum[icingacli] =  2.4.0-2.el6
icingaweb2 = 2.4.0

This is the exception:

```shell
* icinga2_feature[command] action enable

    Error executing action `enable` on resource 'icinga2_feature[command]'
        
    RuntimeError
    ------------
    feature not available - command
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/icinga2/libraries/resource_feature.rb:34:in `block in <class:Icinga2Feature>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb
    
     95: icinga2_feature 'command'
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb:95:in `from_file'
    
    icinga2_feature("command") do
      provider Chef::Provider::Icinga2Feature
      action :enable
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      provides :icinga2_feature
      declared_type :icinga2_feature
      cookbook_name "icinga2"
      recipe_name "server_web2"
    end
    

Running handlers:
[2017-01-18T16:10:01+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-01-18T16:10:01+00:00] ERROR: Exception handlers complete
Chef Client failed. 13 resources updated in 32 seconds
[2017-01-18T16:10:01+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-01-18T16:10:01+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-01-18T16:10:01+00:00] ERROR: icinga2_feature[command] (icinga2::server_web2 line 95) had an error: RuntimeError: feature not available - command
[2017-01-18T16:10:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by vkhatri** [comment]
weird, this should not fail.

I do not suspect it is caused by ruby version, chef-client uses embedded ruby.

**Comment by luijar** [comment]
I also tried a diff version, same result.

**Comment by luijar** [comment]
@vkhatri do you have any ideas or something I can look into? We're running a big monitoring solution that I'm trying to upload cookbooks to and we're a bit under the water.

Any help would be appreciated.

**Comment by luijar** [comment]
@vkhatri any timeframe on this? If there's any way I can rollback to a previous version I would that as well. We were on 2.6.5. If I go back to that, I will get the wrong GIT repo issue. So, kind of stuck at this point. If this gets escalated we might drop this solution.

**Comment by dnsmichi** [comment]
Patching the old cookbook you've installed and update to the current git repo isn't an option? (at least I would apply such a workaround if it is urgent)

**Comment by luijar** [comment]
Thanks @dnsmichi that's exactly what we did this morning. It's a hack, but it fixes the issue. We'll try this back again when the fix is pushed to the marketplace.

**Comment by vkhatri** [comment]
@luijar Could you share the OS details, especially the platform version.

I ran kitchen tests and did not see any issue.

Also, could you please share the output of below command?

```shell
# icinga2 feature list

# ls /etc/icinga2/features-available

```

for some reason, resource `icinga2_feature[command]` is unable to find the `command.conf` under `/etc/icinga2/features-available`

**Comment by luijar** [comment]
Thanks @vkhatri Those instructions helped me resolve my issue. In fact the features were all missing for some reason. I don't know what that is, but I suspect it's our error somehow. I was able to SCP the features from our second Icinga master server and things are back to normal. Again, I don't know if this is our mistake or something else. Here's the info you requested anyways, perhaps it's an issue in the chef-icinga scripts: 

Before the fix, running icinga2 feature list: 
```
Disabled features: 
Enabled features: ido-mysql
```

the /etc/icinga2/features-available only had ido-mysql

**Comment by vkhatri** [comment]
@luijar Glad to see you got it working. Cookbook does not `create/delete` features configuration files directly, it relies on `/usr/sbin/icinga2 feature [enable|disable]`.
