### ISSUE TITLE
Enable SSL for web

### ISSUE THREAD

**Issue by dpnl87** [Icinga/chef-icinga2#264]
Currently the classic and icingaweb2 are deployed without SSL. 

IMHO we should by default enable SSL for security reasons. Most distributions have ready to use self generated SSL certs for testing purpose. With attributes we could point to vaild SSL certs on te system.

**Comment by vkhatri** [comment]
Sound good to me. Please feel free to submit a PR.

**Comment by vkhatri** [comment]
Closing in favor of https://github.com/Icinga/chef-icingaweb2/issues/6
