### ISSUE TITLE
wrong icinga2 version install for ubuntu 14.04.5

### ISSUE THREAD

**Issue by zabudskyi** [Icinga/chef-icinga2#272]
I use "icinga2::core_install" recipe  at ubuntu 14.04.5 and get 
```
    STDERR: E: Version '2.6.1-1~ppa1~trusty1' for 'icinga2' was not found
    ---- End output of apt-get -q -y install icinga2=2.6.1-1~ppa1~trusty1 ----
    Ran apt-get -q -y install icinga2=2.6.1-1~ppa1~trusty1 returned 100

```
Right version in repo http://packages.icinga.org/ubuntu/dists/icinga-trusty/main/binary-i386/Packages is `2.6.1-1~ppa1~trusty2`

**Comment by vkhatri** [comment]
Sorry about that, fixed in `v2.9.3`.

**Comment by zabudskyi** [comment]
Thanks. Now it works. 

In Ubuntu 16.04, I have this issue.
```
Recipe: apache2::mod_php5
  * apt_package[libapache2-mod-php5] action install
    * No candidate version available for libapache2-mod-php5
    ================================================================================
    Error executing action `install` on resource 'apt_package[libapache2-mod-php5]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for libapache2-mod-php5

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/apache2/recipes/mod_php5.rb

     30:   package 'libapache2-mod-php5'
     31: when 'arch'
```

**Comment by vkhatri** [comment]
@zabudskyi Cookbook was modified to use `php7` for ubuntu 16.04+ and hence `mod_php5` module was disabled.

Not sure, why run_list still including apache2 module `mod_php5`, will take a look.

**Comment by zabudskyi** [comment]
@vkhatri I ran cookbook at clean system and there wasn't this problem. Sorry for misinforming.

**Comment by zabudskyi** [comment]
@vkhatri Now install version for  Ubuntu16 is 2.6.2-1~ppa1~xenial**1** and _"1 -> 2"_fix   breaks this installation. 
`default['icinga2']['version']` attribute can't help because `~ppa1~xenial2` part is added in cookbook.

**Comment by formorer** [comment]
Speaking as the packager it is not really a good idea to hardcode such versions.

**Comment by vkhatri** [comment]
@formorer I agree, it has been a struggle following the versions (which change almost with every release). But, cookbook should offer version lock.

Would appreciate any pointers and best practices. I believe `puppet-icinga2` module does not enforce version on package install.

@zabudskyi TBH, cookbook is not fully tested for Ubuntu Xenial. But, it is not reflecting in the documentation. Will work on it.

Perhaps, we want to set `default['icinga2']['ignore_version'] = true`.

**Comment by zabudskyi** [comment]
@vkhatri Thanks, `default['icinga2']['ignore_version'] = true `worked for me.
Now I'm trying to install pnp module with `node['icinga2']['pnp'] = true ` and again get php5 error.

```
  * apt_package[php5-cli] action install
    * No candidate version available for php5-cli
    ================================================================================
    Error executing action `install` on resource 'apt_package[php5-cli]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for php5-cli

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rrdtool/recipes/install.rb

     32:   package p
     33: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rrdtool/recipes/install.rb:32:in `block in from_file'

    apt_package("php5-cli") do
      package_name "php5-cli"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "rrdtool"
      recipe_name "install"
    end

    Platform:
    ---------
    x86_64-linux
```

**Comment by vkhatri** [comment]
Icinga2 ClassicUI is deprecated and updated packages repository to use packages.icinga.com.
