### ISSUE TITLE
The fqdn is not evaluated at runtime

### ISSUE THREAD

**Issue by tonnenpinguin** [Icinga/chef-icinga2#276]
When chef is running, the icinga2 cookbook sets the values of it's constants in attributes.rb during the load phase. However, if the hostname/fqdn is changed in another cookbook (e.g. the hostname cookbook) during the same run, these values are not updated anymore and therefore the fqdn being used is the old one.
Is this the intended behaviour or is there anything one can do to use the actual fqdn at runtime?

**Comment by vkhatri** [comment]
@tonnenpinguin Cookbook is using the actual `fqdn`.

attributes/server_constants.rb:
```
default['icinga2']['constants']['NodeName'] = node['fqdn']
```

You may configure `default['icinga2']['constants']['NodeName']` attribute as per your wrapper cookbook attribute.

**Comment by tonnenpinguin** [comment]
I'll give it a try, thanks!
