### ISSUE TITLE
Documentation: icinga2_endpoint action

### ISSUE THREAD

**Issue by dodizzle** [Icinga/chef-icinga2#291]
Version 2.9.3
For the icinga2_endpoint it says the actions available are :enable or :disable with :enable being the default.
When the actual actions are :create or :delete.

**Comment by vkhatri** [comment]
@dodizzle Thank you for reporting, will check it out.

**Comment by vkhatri** [comment]
Updating LWRP.md.

**Comment by vkhatri** [comment]
Fixed.
