### ISSUE TITLE
Split cookbook

### ISSUE THREAD

**Issue by vills** [Icinga/chef-icinga2#293]
Currently, cookbook logic is very complex. It is hard to maintain it.

How about to split this cookbook to different cookbooks? Let's say, cookbook for:
- icinga2 server/client
- icingaweb2
- classic-ui

**Comment by vkhatri** [comment]
IMHO, splitting `icingaweb2` or `classic-ui` recipes to its own cookbook should not make much of the difference. They are single recipe resource collection but have the dependency on `icinga2` packages and services.

However, we can certainly merge recipes `server_object_*` into `server_objects`. 
Perhaps, we can split recipe `server_pnp` to its own wrapper cookbook.

Please let me know your thoughts. I do agree on the complexity of the cookbook.

I think updating the cookbook for Chef 13 may bring some simplicity.

**Comment by vills** [comment]
As for my opinion, icinga(-core) and icingaweb is different services, that should be placed in different cookbooks. Maybe there is no need to split icingaweb2 and classic-ui, but sure core and web should be splitted.

We can return back here after updating cookbook for Chef 13.

**Comment by vkhatri** [comment]
SGTM

**Comment by vkhatri** [comment]
I have started working on splitting the cookbook. Will create issues shortly.

**Comment by vkhatri** [comment]
Local testing completed:
- icinga2repo - cookbook for icinga2 package yum/apt repository
- icinga2classicui - cookbook for icinga2 classic ui setup

Pending:
- icingaweb2 - cookbook for icingaweb2 setup
- icinga2 - core icinga2 server cookbook

**Comment by vkhatri** [comment]
New cookbooks.

- icinga2repo - cookbook for icinga2 package yum/apt repository
- icinga2classicui - cookbook for icinga2 classic ui setup
- icingaweb2 - cookbook for icingaweb2 setup
- icinga2 - core icinga2 server cookbook
- icinga2client - icinga2 client cookbook

**Comment by dnsmichi** [comment]
If you need an additional opinion - drop the classicui cookbook. The config files and meta packages for that are gone in v2.8. `icingaweb2` is the main developed UI :)

Thanks for your hard work in this 👍

**Comment by vkhatri** [comment]
Sure. I have already created and tested `icinga2classicui` chef cookbook locally. 

IMHO, I want to keep it for now in favor of the community. 

We can deprecate it post icinga2 `v2.8` release. 

Let me know your thoughts.

**Comment by vkhatri** [comment]
Never mind, `v2.8` is out.

**Comment by vkhatri** [comment]
Created different cookbooks for `icingaweb2`, `icinga2client`, and `icinga2repo`.

Closing.
