### ISSUE TITLE
Fix tests again before merging something

### ISSUE THREAD

**Issue by vills** [Icinga/chef-icinga2#296]
Tests should fixed again after #292, but before any other changes in repo.

We'll do it shortly.

**Comment by vills** [comment]
Problem with tests is: there is no version 2.7.0 in repositories in ubuntu and centos.
@vkhatri why cookbook use repositories other, than packages.icinga.com?

**Comment by vkhatri** [comment]
Last time I checked while I was working on an issue, official repository was not getting all the builds.

Perhaps it has changed since then, I will take a look.

**Comment by vkhatri** [comment]
@vills Travis is passing now. Closing.

**Comment by vills** [comment]
Perfect 👍

**Comment by vills** [comment]
Heh, not perfect: https://travis-ci.org/Icinga/chef-icinga2/jobs/266463996
