### ISSUE TITLE
create new repo for chef-icinga*

### ISSUE THREAD

**Issue by vkhatri** [Icinga/chef-icinga2#304]
@dnsmichi As per #293 , we have decided to move web and classic ui resources to a separate cookbook.

Please create another git repo `chef-icinga2ui`.

This new cookbook will depend on `icinga2` cookbook for common attributes/resources/etc.

@vills

**Comment by vkhatri** [comment]
Currently working on #293

**Comment by vkhatri** [comment]
@dnsmichi We need to create GitHub repositories listed below.

- chef-icinga2repo - cookbook for icinga2 package yum/apt repository
- chef-icinga2classicui - cookbook for icinga2 classic ui setup
- chef-icingaweb2 - cookbook for icingaweb2 setup
- chef-icinga2 - core icinga2 server setup
- chef-icinga2client - icinga2 client setup

**Comment by vkhatri** [comment]
@vills ^^

**Comment by vills** [comment]
Perfect! :-)

**Comment by dnsmichi** [comment]
See my comment in #293 - I agree on everything except for classicui.

**Comment by dnsmichi** [comment]
https://github.com/Icinga/chef-icinga2repo
https://github.com/Icinga/chef-icingaweb2
https://github.com/Icinga/chef-icinga2client

Same permissions as here, please try it out @vkhatri

**Comment by dnsmichi** [comment]
Btw - @bobapple should be your first contact with infrastructure requirements. I did not read your initial issue, sorry about that.

**Comment by vills** [comment]
@vkhatri is chef-icinga2repo cookbook should do something except adding repositories?

**Comment by vkhatri** [comment]
@vills Yes. `chef-icinga2repo` is the icinga2 yum/apt repository shared among the cookbooks.

@dnsmichi Thank you for creating the repositories.

**Comment by vkhatri** [comment]
@vills It does not do anything else other than repository management.
