### ISSUE TITLE
Bump Apache Support from 3.2.2 to 3.3.0

### ISSUE THREAD

**Issue by kjbweb** [Icinga/chef-icinga2#309]
## Expected Behavior
I'd be able to upgrade the Apache dependency within our cookbook from 3.2.2 to 3.3.0.

## Current Behavior
Because sous-chef's jumped from 3.2.2 to 3.3.0, our cookbook fails to converge.  The icinga2 cookbook is pessimisticly locking us to Apache's 3.2.X series of cookbooks which are ageing: https://github.com/sous-chefs/apache2/releases 

## Context
I'm upgrading to Apache 3.3.0 to resolve https://github.com/sous-chefs/apache2/pull/422

**Comment by vkhatri** [comment]
Will fix shortly (should be using `>=`). Thank you for reporting!

**Comment by vkhatri** [comment]
Bumping apache2 and other cookbooks to latest version.

**Comment by vkhatri** [comment]
Updated apache2 cookbook to v5.0.1.

Closing this issue.

Icingaweb2 is now maintained by another repository https://github.com/Icinga/chef-icingaweb2
